server:
  port: 8080
  error:
    include-message: always

eureka:
  instance:
    hostname: gateway
  client:
    service-url:
      defaultZone: http://eureka:8761/eureka/

spring.zipkin.skip.pattern:
  - /actuator
  - /kibana
  - /zipkin
  - /grafana

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-components: always
      show-details: always
  metrics:
    tags:
      application: ${spring.application.name}
  tracing:
    sampling:
      probability: 1.0
  zipkin:
    tracing:
      endpoint: http://zipkin:9411/api/v2/spans

logging:
  level:
    xyz.mpdn.gateway: INFO
    root: INFO
#    reactor.netty.http.client: DEBUG
  pattern:
    level: "%5p [${spring.application.name},%X{type:-application}, %X{traceId:-},%X{spanId:-}]"

spring:
  profiles:
    active: dev
  application:
    name: gateway-service
  security:
    oauth2:
     client:
       registration:
         keycloak:
           client-id: msFundamentals
           authorization-grant-type: authorization_code
           scope: openid
       provider:
         keycloak:
           issuer-uri: http://host.docker.internal:43000/realms/msFundamentals
           user-name-attribute: preferred_username

  cloud:
    gateway:
      routes:
        - id: song
          uri: lb://SONG-SERVICE
          predicates:
            - Path=/api/v1/song**,/api/v1/song/**
        - id: resource
          uri: lb://RESOURCE-SERVICE
          predicates:
            - Path=/api/v1/resource**,/api/v1/resource/**
        - id: storage
          uri: lb://STORAGE-SERVICE
          predicates:
            - Path=/api/v1/storage**,/api/v1/storage/**
        - id: eureka
          uri: http://eureka:8761
          predicates:
            - Path=/es/**,/es**
          filters:
            - RewritePath=es(?<segment>.*),/$\{segment}
        - id: eureka-resources
          uri: http://eureka:8761
          predicates:
            - Path=/eureka/**,/eureka**
        - id: zipkin
          uri: http://zipkin:9411
          predicates:
            - Path=/zipkin/**,/zipkin**
        - id: grafana
          uri: http://grafana:3000
          predicates:
            - Path=/grafana/**,/grafana**
          filters:
            - PreserveHostHeader
        - id: kibana
          uri: http://kibana:5601
          predicates:
            - Path=/kibana/**,/kibana**
      default-filters:
        - TokenRelay

